enum DiningAndEntertaining {
  dinnerwareSets,
  flatware,
  glassware,
  mugs,
  plates,
  bowls,
  serverware,
  outdoorDinnerware,
  beverageDispensers,
  kidsTableware,
  kitchenTextiles,
  travelMugs,
  saltAndPepperShakers,
  barware,
}